"""Compare final fixed-demo mesh pair against stated numerical criteria."""
import argparse,json
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('run',type=Path);a=p.parse_args()
coarse=json.loads((a.run/'case-hex-coarse-corrected/summary.json').read_text());fine=json.loads((a.run/'case-hex-fine-corrected/summary.json').read_text())
def accept(s):
    r=s['last100_residual_max']
    return {'mass':s['mass_imbalance_fraction']<=.001,'energy':s['energy_imbalance_with_inlet_diffusion_fraction']<=.01,'temperature_drift':s['final_100_iteration_ranges']['heatedMax']<=.1,'pressure_drift':s['pressure_drop_drift_fraction']<=.01,'residual_initial':len(r)==8 and all(x['initial']<=1e-5 for x in r.values()),'linear_residual':len(r)==8 and all(x['linear_final']<=1e-7 for x in r.values())}
dt=abs(fine['monitor_last']['heatedMax']-coarse['monitor_last']['heatedMax']);dp=abs(fine['pressure_drop_Pa']-coarse['pressure_drop_Pa'])/fine['pressure_drop_Pa'];rise=dt/(fine['monitor_last']['heatedMax']-300)
checks={'coarse':accept(coarse),'fine':accept(fine),'mesh':{'temperature_absolute':dt<=1,'temperature_rise_relative':rise<=.05,'pressure_relative':dp<=.05}}
thermal=json.loads((a.run/'thermal/estimates.json').read_text());sat=thermal['saturation_temperatures_at_outlet_bounds_K'][0]
# The conservative saturation comparison is valid only if actual pressure never falls below outlet.
if fine['minimum_absolute_pressure_Pa']<111325-1e-6:raise ValueError('Recompute saturation at lower actual minimum pressure')
result={'status':'candidate_for_independent_review','wall_treatment_review':{'coarse':coarse['yplus_face_count_distribution'],'fine':fine['yplus_face_count_distribution'],'fine_spatial':fine['yplus_spatial_review'],'note':'Nominal y+30 log-layer lower guideline is not a sharp cutoff; near-threshold extent requires engineering review.'},'numerical_checks':checks,'all_numerical_checks_pass':all(all(v.values()) for v in checks.values()),'mesh_changes':{'heated_maximum_K':dt,'heated_temperature_rise_fraction':rise,'pressure_drop_fraction':dp},'temperature_limit_K':500,'heated_maximum_K':fine['monitor_last']['heatedMax'],'temperature_limit_met':fine['monitor_last']['heatedMax']<=500,'mass_flow_kg_s':.5,'volume_flow_L_s':.5/thermal['water_properties']['density_kg_m3']*1000,'outlet_absolute_pressure_bar':1.11325,'outlet_gauge_pressure_bar':.1,'ambient_reference_bar':1.01325,'pressure_drop_bar':fine['pressure_drop_Pa']/1e5,'inlet_absolute_pressure_bar':fine['monitor_last']['inletPressure']/1e5,'maximum_wetted_temperature_K':fine['monitor_last']['wettedMax'],'minimum_absolute_pressure_Pa':fine['minimum_absolute_pressure_Pa'],'saturation_temperature_at_minimum_pressure_K':sat,'conservative_wetted_subcooling_K':sat-fine['monitor_last']['wettedMax'],'required_subcooling_margin_K':10,'subcooling_margin_met':sat-fine['monitor_last']['wettedMax']>=10,'coolant_sensible_heat_pickup_W':fine['sensible_heat_pickup_W'],'total_applied_heat_W':240,'caveats':['Two-mesh sensitivity is not formal grid independence or experimental validation.','Constant properties, steady single-phase RANS, smooth walls, uniform inlet turbulence5%; external surfaces adiabatic without incident irradiation.','No whole-loop pump, startup transient or boiling model was simulated. Wetted temperatures below saturation support single-phase applicability for this baseline.','Liquid constant-property h=cpT omits pressure-dependent enthalpy; mechanical heating fidelity limited at this low-dissipation operating point.','Only approved demo geometry supported; fixed shape retained.'],'source_cases':['case-hex-coarse-corrected','case-hex-fine-corrected']}
(a.run/'cfd-results.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
